import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * @description Is responsible for rendering a HTML body element containing its
 * children component.
 * 
 * @param {Readonly<{
 *   children: React.ReactNode;
 * }>} .children - component that will be rendered within the `<html>` and `<body>`
 * tags of the HTML document, according to the provided code.
 * 
 * @returns {HTML element} an HTML document with a specific class name applied to the
 * body element and the provided child content inside it.
 * 
 * 	* `html`: This is an HTML element that contains the content of the page.
 * 	* `body`: This is a HTML body element that contains the content of the page within
 * the `html` element.
 * 	* `className`: This is a class name that is added to the `body` element.
 * 
 * 	These properties provide a basic structure for an HTML page, including a root
 * element (`html`), a containing element (`body'), and a class name for styling purposes.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
